// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtUo2fnrch4jo4J1ZTZE1FsEhdMBN-J_I',
    appId: '1:169740275266:web:72a81d5b54dcf4cbfee7db',
    messagingSenderId: '169740275266',
    projectId: 'sharepactdev',
    authDomain: 'sharepactdev.firebaseapp.com',
    storageBucket: 'sharepactdev.appspot.com',
    measurementId: 'G-KFXE2CL24V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqwUw_mZQqJ8T3i0ew1GAQLO1nufzAuC8',
    appId: '1:169740275266:android:00218a9baaf071b5fee7db',
    messagingSenderId: '169740275266',
    projectId: 'sharepactdev',
    storageBucket: 'sharepactdev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNa3wLD32yQP9bJ2s9EuV86EJNGjO9c28',
    appId: '1:169740275266:ios:79a84c07248c2389fee7db',
    messagingSenderId: '169740275266',
    projectId: 'sharepactdev',
    storageBucket: 'sharepactdev.appspot.com',
    iosBundleId: 'com.example.sharepactApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNa3wLD32yQP9bJ2s9EuV86EJNGjO9c28',
    appId: '1:169740275266:ios:79a84c07248c2389fee7db',
    messagingSenderId: '169740275266',
    projectId: 'sharepactdev',
    storageBucket: 'sharepactdev.appspot.com',
    iosBundleId: 'com.example.sharepactApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtUo2fnrch4jo4J1ZTZE1FsEhdMBN-J_I',
    appId: '1:169740275266:web:d0d5951e2ee8ee0ffee7db',
    messagingSenderId: '169740275266',
    projectId: 'sharepactdev',
    authDomain: 'sharepactdev.firebaseapp.com',
    storageBucket: 'sharepactdev.appspot.com',
    measurementId: 'G-0CGJJ64G0E',
  );

}